pipeline {
  agent {
    kubernetes {
      yaml """
apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: jenkins-kaniko
spec:
  serviceAccountName: jenkins-sa
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:v1.16.0-debug
      imagePullPolicy: Always
      command: ['sleep']
      args: ['99d']
    - name: git
      image: alpine/git
      command: ['sleep']
      args: ['99d']
"""
    }
  }

  environment {
    IMAGE_TAG    = "v${BUILD_NUMBER}"
    REPO_URL     = "github.com/Maksym-Zyza/devops-ci-cd.git"
  }

  stages {
    stage('Debug: Find Dockerfile') {
        steps {
            container('git') {
            sh """
                echo "=== ПОШУК DOCKERFILE ==="
                find ${WORKSPACE} -name Dockerfile
                echo "=== ПОТОЧНА ДИРЕКТОРІЯ ==="
                pwd
            """
            }
        }
    }

    stage('Build & Push Docker Image') {
      steps {
        container('kaniko') {
            sh """
            /kaniko/executor \
            --context ${WORKSPACE}/django-docker-project \
            --dockerfile Dockerfile \
            --destination ${ECR_REPOSITORY_URL}:${IMAGE_TAG} \
            --cache=true
            """
        }
      }
    }

    stage('Update Chart Tag in Git') {
      steps {
        container('git') {
          withCredentials([usernamePassword(credentialsId: 'github-token', usernameVariable: 'GIT_USERNAME', passwordVariable: 'GIT_PAT')]) {
            sh """
                # 1. Дозволяємо Git працювати з цією директорією
                git config --global --add safe.directory '*'

                # 2. Налаштовуємо Git
                git config user.email "jenkins@localhost"
                git config user.name "jenkins"
                
                # 3. Оновлюємо тег у values.yaml (шлях ми підтвердили через Debug)
                sed -i "s|repository: .*|repository: ${ECR_REPOSITORY_URL}|g" lesson-db-module/charts/django-app/values.yaml
                sed -i "s/tag: .*/tag: ${IMAGE_TAG}/g" lesson-db-module/charts/django-app/values.yaml

                # 4. Комітимо та пушимо зміни
                git add lesson-db-module/charts/django-app/values.yaml
                git commit -m "Update image tag to ${IMAGE_TAG} [skip ci]"
                
                # Пушимо в гілку lesson-db-module
                git push https://${GIT_USERNAME}:${GIT_PAT}@github.com/Maksym-Zyza/devops-ci-cd.git HEAD:lesson-db-module
            """
          }
        }
      }
    }
  }
}