pipeline {
  agent {
    kubernetes {
      yaml """
apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: jenkins-kaniko
spec:
  serviceAccountName: jenkins-sa
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:v1.16.0-debug
      imagePullPolicy: Always
      command: ['sleep']
      args: ['99d']
    - name: git
      image: alpine/git
      command: ['sleep']
      args: ['99d']
    - name: python
      image: python:3.9-slim
      command: ['sleep']
      args: ['99d']
      env:
        - name: DATABASE_HOST
          value: "localhost"
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_NAME
          value: "test_db"
        - name: DATABASE_USER
          value: "postgres"
        - name: DATABASE_PASSWORD
          value: "postgres"
    - name: postgres
      image: postgres:13-alpine
      env:
        - name: POSTGRES_DB
          value: "test_db"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
      ports:
        - containerPort: 5432
          name: postgres
"""
    }
  }

  environment {
    IMAGE_TAG    = "v${BUILD_NUMBER}"
    REPO_URL     = "github.com/Maksym-Zyza/devops-ci-cd.git"
  }

  stages {
    stage('Unit Tests') {
      steps {
        container('python') {
          sh """
            echo "Installing dependencies for testing..."
            # Встановлюємо netcat та бібліотеки для psycopg2
            apt-get update && apt-get install -y netcat-openbsd gcc libpq-dev

            pip install -r django-docker-project/requirements.txt
            
            echo "Waiting for PostgreSQL to be ready..."
            while ! nc -z localhost 5432; do   
              sleep 1
            done
            echo "PostgreSQL started"

            echo "Running Django Tests..."
            cd django-docker-project/app && python manage.py test
          """
        }
      }
    }

    stage('Security: SAST (Bandit)') {
      steps {
        container('python') {
          sh """
            echo "Installing Bandit..."
            pip install bandit
            echo "Running Bandit Scan..."
            bandit -r django-docker-project/app || true
          """
        }
      }
    }

    stage('Security: Container Scan (Trivy)') {
      steps {
        container('git') {
          sh """
            echo "Installing Trivy..."
            apk add --no-cache curl
            curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

            echo "Running Trivy Config Scan..."
            trivy config .
            
            echo "Running Trivy Filesystem Scan..."
            trivy fs --scanners vuln,secret .
          """
        }
      }
    }

    stage('Build & Push Docker Image') {
      steps {
        container('kaniko') {
            sh """
            /kaniko/executor \
            --context ${WORKSPACE}/django-docker-project \
            --dockerfile Dockerfile \
            --destination ${ECR_REPOSITORY_URL}:${IMAGE_TAG} \
            --cache=true
            """
        }
      }
    }

    stage('Update Chart Tag in Git') {
      steps {
        container('git') {
          withCredentials([usernamePassword(credentialsId: 'github-token', usernameVariable: 'GIT_USERNAME', passwordVariable: 'GIT_PAT')]) {
            sh """
                git config --global --add safe.directory '*'
                git config user.email "jenkins@localhost"
                git config user.name "jenkins"
                
                sed -i "s|repository: .*|repository: ${ECR_REPOSITORY_URL}|g" final-project/charts/django-app/values.yaml
                sed -i "s/tag: .*/tag: ${IMAGE_TAG}/g" final-project/charts/django-app/values.yaml

                git add final-project/charts/django-app/values.yaml
                git commit -m "Update image tag to ${IMAGE_TAG} [skip ci]"
                
                git push https://${GIT_USERNAME}:${GIT_PAT}@github.com/Maksym-Zyza/devops-ci-cd.git HEAD:final-project
            """
          }
        }
      }
    }
  }
}
