pipeline {
  agent {
    kubernetes {
      yaml """
apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: jenkins-kaniko
spec:
  serviceAccountName: jenkins-sa
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:v1.16.0-debug
      imagePullPolicy: Always
      command: ['sleep']
      args: ['99d']
    - name: git
      image: alpine/git
      command: ['sleep']
      args: ['99d']
"""
    }
  }

  environment {
    ECR_REGISTRY = "088581047201.dkr.ecr.us-west-2.amazonaws.com"
    IMAGE_NAME   = "django-app"
    IMAGE_TAG    = "v${BUILD_NUMBER}"
    REPO_URL     = "github.com/Maksym-Zyza/devops-ci-cd.git"
  }

  stages {
    stage('Build & Push Docker Image') {
      steps {
        container('kaniko') {
            sh """
            /kaniko/executor \
            --context ${WORKSPACE}/lesson-4/django-docker-project \
            --dockerfile Dockerfile \
            --destination ${ECR_REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG} \
            --cache=true
            """
        }
      }
    }

    stage('Update Chart Tag in Git') {
      steps {
        container('git') {
          withCredentials([usernamePassword(credentialsId: 'github-token', usernameVariable: 'GIT_USERNAME', passwordVariable: 'GIT_PAT')]) {
            sh """
              # Налаштовуємо Git
              git config user.email "jenkins@localhost"
              git config user.name "jenkins"
              
              # Шлях від кореня репозиторію
              sed -i "s/tag: .*/tag: ${IMAGE_TAG}/g" lesson-8-9/lesson-8-9/charts/django-app/values.yaml

              # Стейджимо та пушимо зміни прямо в поточну гілку
              git add lesson-8-9/lesson-8-9/charts/django-app/values.yaml
              git commit -m "Update image tag to ${IMAGE_TAG} [skip ci]"
              
              # Пушимо через HTTPS з токеном
              git push https://${GIT_PAT}@${REPO_URL} HEAD:lesson-8-9
            """
          }
        }
      }
    }
  }
}